// Built-in gazetteer for extracting locations from news text.
// Each entry: { names: [...], lat, lng, region }
// Names are checked longest-first to avoid partial matches.

const RAW = [
  // === COUNTRIES ===
  { names: ['United States', 'U.S.', 'USA'], lat: 39.8, lng: -98.6, region: 'North America' },
  { names: ['United Kingdom', 'U.K.', 'Britain'], lat: 55.4, lng: -3.4, region: 'Europe' },
  { names: ['United Arab Emirates', 'UAE'], lat: 24.5, lng: 54.7, region: 'Middle East' },
  { names: ['South Korea', 'S. Korea'], lat: 36.5, lng: 127.0, region: 'East Asia' },
  { names: ['North Korea', 'DPRK'], lat: 40.0, lng: 127.0, region: 'East Asia' },
  { names: ['South Africa'], lat: -30.6, lng: 25.0, region: 'Africa' },
  { names: ['South Sudan'], lat: 6.8, lng: 31.6, region: 'Africa' },
  { names: ['Sri Lanka'], lat: 7.9, lng: 80.8, region: 'South Asia' },
  { names: ['Saudi Arabia'], lat: 24.7, lng: 45.1, region: 'Middle East' },
  { names: ['New Zealand'], lat: -41.3, lng: 174.8, region: 'Oceania' },
  { names: ['Costa Rica'], lat: 10.0, lng: -84.1, region: 'South America' },
  { names: ['Czech Republic', 'Czechia'], lat: 49.8, lng: 15.5, region: 'Europe' },
  { names: ['Dominican Republic'], lat: 18.7, lng: -70.2, region: 'South America' },
  { names: ['El Salvador'], lat: 13.8, lng: -88.9, region: 'South America' },
  { names: ['Ivory Coast', "Cote d'Ivoire"], lat: 7.5, lng: -5.5, region: 'Africa' },
  { names: ['Bosnia', 'Bosnia and Herzegovina'], lat: 43.9, lng: 17.7, region: 'Europe' },
  { names: ['Afghanistan'], lat: 33.9, lng: 67.7, region: 'Central Asia' },
  { names: ['Albania'], lat: 41.2, lng: 20.2, region: 'Europe' },
  { names: ['Algeria'], lat: 28.0, lng: 1.7, region: 'Africa' },
  { names: ['Angola'], lat: -11.2, lng: 17.9, region: 'Africa' },
  { names: ['Argentina'], lat: -38.4, lng: -63.6, region: 'South America' },
  { names: ['Armenia'], lat: 40.1, lng: 45.0, region: 'Central Asia' },
  { names: ['Australia'], lat: -25.3, lng: 133.8, region: 'Oceania' },
  { names: ['Austria'], lat: 47.5, lng: 14.6, region: 'Europe' },
  { names: ['Azerbaijan'], lat: 40.1, lng: 47.6, region: 'Central Asia' },
  { names: ['Bahrain'], lat: 26.1, lng: 50.6, region: 'Middle East' },
  { names: ['Bangladesh'], lat: 23.7, lng: 90.4, region: 'South Asia' },
  { names: ['Belarus'], lat: 53.7, lng: 27.9, region: 'Europe' },
  { names: ['Belgium'], lat: 50.5, lng: 4.5, region: 'Europe' },
  { names: ['Bolivia'], lat: -16.3, lng: -63.6, region: 'South America' },
  { names: ['Brazil'], lat: -14.2, lng: -51.9, region: 'South America' },
  { names: ['Bulgaria'], lat: 42.7, lng: 25.5, region: 'Europe' },
  { names: ['Myanmar', 'Burma'], lat: 19.8, lng: 96.2, region: 'Southeast Asia' },
  { names: ['Burkina Faso'], lat: 12.4, lng: -1.6, region: 'Africa' },
  { names: ['Cambodia'], lat: 12.6, lng: 105.0, region: 'Southeast Asia' },
  { names: ['Cameroon'], lat: 5.9, lng: 10.1, region: 'Africa' },
  { names: ['Canada'], lat: 56.1, lng: -106.3, region: 'North America' },
  { names: ['Chad'], lat: 15.5, lng: 18.7, region: 'Africa' },
  { names: ['Chile'], lat: -35.7, lng: -71.5, region: 'South America' },
  { names: ['China'], lat: 35.9, lng: 104.2, region: 'East Asia' },
  { names: ['Colombia'], lat: 4.6, lng: -74.1, region: 'South America' },
  { names: ['Congo', 'DRC'], lat: -4.3, lng: 15.3, region: 'Africa' },
  { names: ['Croatia'], lat: 45.1, lng: 15.2, region: 'Europe' },
  { names: ['Cuba'], lat: 21.5, lng: -77.8, region: 'South America' },
  { names: ['Cyprus'], lat: 35.1, lng: 33.4, region: 'Europe' },
  { names: ['Denmark'], lat: 56.3, lng: 9.5, region: 'Europe' },
  { names: ['Ecuador'], lat: -1.8, lng: -78.2, region: 'South America' },
  { names: ['Egypt'], lat: 26.8, lng: 30.8, region: 'Middle East' },
  { names: ['Estonia'], lat: 58.6, lng: 25.0, region: 'Europe' },
  { names: ['Ethiopia'], lat: 9.1, lng: 40.5, region: 'Africa' },
  { names: ['Finland'], lat: 61.9, lng: 25.7, region: 'Europe' },
  { names: ['France'], lat: 46.2, lng: 2.2, region: 'Europe' },
  { names: ['Georgia'], lat: 42.3, lng: 43.4, region: 'Central Asia' },
  { names: ['Germany'], lat: 51.2, lng: 10.5, region: 'Europe' },
  { names: ['Ghana'], lat: 7.9, lng: -1.0, region: 'Africa' },
  { names: ['Greece'], lat: 39.1, lng: 21.8, region: 'Europe' },
  { names: ['Guatemala'], lat: 15.8, lng: -90.2, region: 'South America' },
  { names: ['Haiti'], lat: 19.0, lng: -72.3, region: 'South America' },
  { names: ['Honduras'], lat: 14.6, lng: -86.2, region: 'South America' },
  { names: ['Hungary'], lat: 47.2, lng: 19.5, region: 'Europe' },
  { names: ['Iceland'], lat: 65.0, lng: -18.0, region: 'Europe' },
  { names: ['India'], lat: 20.6, lng: 79.0, region: 'South Asia' },
  { names: ['Indonesia'], lat: -0.8, lng: 113.9, region: 'Southeast Asia' },
  { names: ['Iran'], lat: 32.4, lng: 53.7, region: 'Middle East' },
  { names: ['Iraq'], lat: 33.2, lng: 43.7, region: 'Middle East' },
  { names: ['Ireland'], lat: 53.1, lng: -7.7, region: 'Europe' },
  { names: ['Israel'], lat: 31.0, lng: 34.9, region: 'Middle East' },
  { names: ['Italy'], lat: 41.9, lng: 12.6, region: 'Europe' },
  { names: ['Jamaica'], lat: 18.1, lng: -77.3, region: 'South America' },
  { names: ['Japan'], lat: 36.2, lng: 138.3, region: 'East Asia' },
  { names: ['Jordan'], lat: 31.0, lng: 36.8, region: 'Middle East' },
  { names: ['Kazakhstan'], lat: 48.0, lng: 67.0, region: 'Central Asia' },
  { names: ['Kenya'], lat: -0.02, lng: 37.9, region: 'Africa' },
  { names: ['Kosovo'], lat: 42.6, lng: 21.0, region: 'Europe' },
  { names: ['Kuwait'], lat: 29.3, lng: 47.5, region: 'Middle East' },
  { names: ['Kyrgyzstan'], lat: 41.2, lng: 74.8, region: 'Central Asia' },
  { names: ['Laos'], lat: 19.9, lng: 102.5, region: 'Southeast Asia' },
  { names: ['Latvia'], lat: 56.9, lng: 24.1, region: 'Europe' },
  { names: ['Lebanon'], lat: 33.9, lng: 35.9, region: 'Middle East' },
  { names: ['Libya'], lat: 26.3, lng: 17.2, region: 'Africa' },
  { names: ['Lithuania'], lat: 55.2, lng: 23.9, region: 'Europe' },
  { names: ['Malaysia'], lat: 4.2, lng: 101.7, region: 'Southeast Asia' },
  { names: ['Mali'], lat: 17.6, lng: -4.0, region: 'Africa' },
  { names: ['Mexico'], lat: 23.6, lng: -102.6, region: 'North America' },
  { names: ['Moldova'], lat: 47.4, lng: 28.4, region: 'Europe' },
  { names: ['Mongolia'], lat: 46.9, lng: 103.8, region: 'East Asia' },
  { names: ['Morocco'], lat: 31.8, lng: -7.1, region: 'Africa' },
  { names: ['Mozambique'], lat: -18.7, lng: 35.5, region: 'Africa' },
  { names: ['Nepal'], lat: 28.4, lng: 84.1, region: 'South Asia' },
  { names: ['Netherlands', 'Holland'], lat: 52.1, lng: 5.3, region: 'Europe' },
  { names: ['Nicaragua'], lat: 12.9, lng: -85.2, region: 'South America' },
  { names: ['Niger'], lat: 17.6, lng: 8.1, region: 'Africa' },
  { names: ['Nigeria'], lat: 9.1, lng: 8.7, region: 'Africa' },
  { names: ['Norway'], lat: 60.5, lng: 8.5, region: 'Europe' },
  { names: ['Oman'], lat: 21.5, lng: 55.9, region: 'Middle East' },
  { names: ['Pakistan'], lat: 30.4, lng: 69.3, region: 'South Asia' },
  { names: ['Palestine', 'Palestinian', 'Gaza', 'West Bank'], lat: 31.9, lng: 35.2, region: 'Middle East' },
  { names: ['Panama'], lat: 8.5, lng: -80.8, region: 'South America' },
  { names: ['Paraguay'], lat: -23.4, lng: -58.4, region: 'South America' },
  { names: ['Peru'], lat: -9.2, lng: -75.0, region: 'South America' },
  { names: ['Philippines'], lat: 13.4, lng: 122.0, region: 'Southeast Asia' },
  { names: ['Poland'], lat: 51.9, lng: 19.1, region: 'Europe' },
  { names: ['Portugal'], lat: 39.4, lng: -8.2, region: 'Europe' },
  { names: ['Qatar'], lat: 25.4, lng: 51.2, region: 'Middle East' },
  { names: ['Romania'], lat: 45.9, lng: 25.0, region: 'Europe' },
  { names: ['Russia', 'Russian'], lat: 61.5, lng: 105.3, region: 'Europe' },
  { names: ['Rwanda'], lat: -1.9, lng: 29.9, region: 'Africa' },
  { names: ['Senegal'], lat: 14.5, lng: -14.5, region: 'Africa' },
  { names: ['Serbia'], lat: 44.0, lng: 21.0, region: 'Europe' },
  { names: ['Singapore'], lat: 1.4, lng: 103.8, region: 'Southeast Asia' },
  { names: ['Slovakia'], lat: 48.7, lng: 19.7, region: 'Europe' },
  { names: ['Slovenia'], lat: 46.2, lng: 14.8, region: 'Europe' },
  { names: ['Somalia'], lat: 5.2, lng: 46.2, region: 'Africa' },
  { names: ['Spain'], lat: 40.5, lng: -3.7, region: 'Europe' },
  { names: ['Sudan'], lat: 12.9, lng: 30.2, region: 'Africa' },
  { names: ['Sweden'], lat: 60.1, lng: 18.6, region: 'Europe' },
  { names: ['Switzerland'], lat: 46.8, lng: 8.2, region: 'Europe' },
  { names: ['Syria', 'Syrian'], lat: 35.0, lng: 38.5, region: 'Middle East' },
  { names: ['Taiwan'], lat: 23.7, lng: 121.0, region: 'East Asia' },
  { names: ['Tajikistan'], lat: 38.9, lng: 71.3, region: 'Central Asia' },
  { names: ['Tanzania'], lat: -6.4, lng: 34.9, region: 'Africa' },
  { names: ['Thailand'], lat: 15.9, lng: 100.9, region: 'Southeast Asia' },
  { names: ['Tunisia'], lat: 34.0, lng: 9.5, region: 'Africa' },
  { names: ['Turkey', 'Türkiye', 'Turkiye'], lat: 39.0, lng: 35.2, region: 'Middle East' },
  { names: ['Turkmenistan'], lat: 39.0, lng: 59.6, region: 'Central Asia' },
  { names: ['Uganda'], lat: 1.4, lng: 32.3, region: 'Africa' },
  { names: ['Ukraine', 'Ukrainian'], lat: 48.4, lng: 31.2, region: 'Europe' },
  { names: ['Uruguay'], lat: -32.5, lng: -55.8, region: 'South America' },
  { names: ['Uzbekistan'], lat: 41.4, lng: 64.6, region: 'Central Asia' },
  { names: ['Venezuela'], lat: 6.4, lng: -66.6, region: 'South America' },
  { names: ['Vietnam'], lat: 14.1, lng: 108.3, region: 'Southeast Asia' },
  { names: ['Yemen'], lat: 15.6, lng: 48.5, region: 'Middle East' },
  { names: ['Zambia'], lat: -13.1, lng: 28.0, region: 'Africa' },
  { names: ['Zimbabwe'], lat: -19.0, lng: 29.2, region: 'Africa' },
  { names: ['Andorra'], lat: 42.5, lng: 1.5, region: 'Europe' },
  { names: ['Antigua and Barbuda', 'Antigua'], lat: 17.1, lng: -61.8, region: 'South America' },
  { names: ['Bahamas'], lat: 25.0, lng: -77.4, region: 'South America' },
  { names: ['Barbados'], lat: 13.2, lng: -59.5, region: 'South America' },
  { names: ['Belize'], lat: 17.2, lng: -88.5, region: 'South America' },
  { names: ['Benin'], lat: 9.3, lng: 2.3, region: 'Africa' },
  { names: ['Bhutan'], lat: 27.5, lng: 90.4, region: 'South Asia' },
  { names: ['Botswana'], lat: -22.3, lng: 24.7, region: 'Africa' },
  { names: ['Brunei'], lat: 4.9, lng: 114.9, region: 'Southeast Asia' },
  { names: ['Burundi'], lat: -3.4, lng: 29.9, region: 'Africa' },
  { names: ['Cabo Verde', 'Cape Verde'], lat: 16.0, lng: -24.0, region: 'Africa' },
  { names: ['Central African Republic', 'CAR'], lat: 6.6, lng: 20.9, region: 'Africa' },
  { names: ['Comoros'], lat: -11.9, lng: 43.9, region: 'Africa' },
  { names: ['Djibouti'], lat: 11.6, lng: 43.1, region: 'Africa' },
  { names: ['Dominica'], lat: 15.4, lng: -61.4, region: 'South America' },
  { names: ['Equatorial Guinea'], lat: 1.7, lng: 10.3, region: 'Africa' },
  { names: ['Eritrea'], lat: 15.2, lng: 39.8, region: 'Africa' },
  { names: ['Eswatini', 'Swaziland'], lat: -26.5, lng: 31.5, region: 'Africa' },
  { names: ['Fiji'], lat: -17.7, lng: 178.1, region: 'Oceania' },
  { names: ['Gabon'], lat: -0.8, lng: 11.6, region: 'Africa' },
  { names: ['Gambia'], lat: 13.4, lng: -15.3, region: 'Africa' },
  { names: ['Grenada'], lat: 12.1, lng: -61.7, region: 'South America' },
  { names: ['Guinea'], lat: 9.9, lng: -11.8, region: 'Africa' },
  { names: ['Guinea-Bissau'], lat: 12.0, lng: -15.2, region: 'Africa' },
  { names: ['Guyana'], lat: 5.0, lng: -58.9, region: 'South America' },
  { names: ['Kiribati'], lat: 1.9, lng: -157.4, region: 'Oceania' },
  { names: ['Lesotho'], lat: -29.6, lng: 28.2, region: 'Africa' },
  { names: ['Liberia'], lat: 6.4, lng: -9.4, region: 'Africa' },
  { names: ['Liechtenstein'], lat: 47.2, lng: 9.6, region: 'Europe' },
  { names: ['Luxembourg'], lat: 49.8, lng: 6.1, region: 'Europe' },
  { names: ['Madagascar'], lat: -18.8, lng: 46.9, region: 'Africa' },
  { names: ['Malawi'], lat: -13.3, lng: 34.3, region: 'Africa' },
  { names: ['Maldives'], lat: 3.2, lng: 73.2, region: 'South Asia' },
  { names: ['Malta'], lat: 35.9, lng: 14.4, region: 'Europe' },
  { names: ['Marshall Islands'], lat: 7.1, lng: 171.2, region: 'Oceania' },
  { names: ['Mauritania'], lat: 21.0, lng: -11.0, region: 'Africa' },
  { names: ['Mauritius'], lat: -20.3, lng: 57.6, region: 'Africa' },
  { names: ['Micronesia'], lat: 6.9, lng: 158.2, region: 'Oceania' },
  { names: ['Monaco'], lat: 43.7, lng: 7.4, region: 'Europe' },
  { names: ['Montenegro'], lat: 42.7, lng: 19.4, region: 'Europe' },
  { names: ['Namibia'], lat: -22.6, lng: 17.1, region: 'Africa' },
  { names: ['Nauru'], lat: -0.5, lng: 166.9, region: 'Oceania' },
  { names: ['North Macedonia', 'Macedonia'], lat: 41.5, lng: 21.7, region: 'Europe' },
  { names: ['Palau'], lat: 7.5, lng: 134.6, region: 'Oceania' },
  { names: ['Papua New Guinea'], lat: -6.3, lng: 143.9, region: 'Oceania' },
  { names: ['Republic of the Congo', 'Congo-Brazzaville'], lat: -0.2, lng: 15.8, region: 'Africa' },
  { names: ['Saint Lucia', 'St. Lucia'], lat: 13.9, lng: -60.97, region: 'South America' },
  { names: ['Samoa'], lat: -13.8, lng: -172.0, region: 'Oceania' },
  { names: ['San Marino'], lat: 43.9, lng: 12.5, region: 'Europe' },
  { names: ['São Tomé and Príncipe', 'Sao Tome'], lat: 0.2, lng: 6.6, region: 'Africa' },
  { names: ['Seychelles'], lat: -4.7, lng: 55.5, region: 'Africa' },
  { names: ['Sierra Leone'], lat: 8.5, lng: -11.8, region: 'Africa' },
  { names: ['Solomon Islands'], lat: -9.4, lng: 160.0, region: 'Oceania' },
  { names: ['Suriname'], lat: 3.9, lng: -56.0, region: 'South America' },
  { names: ['Timor-Leste', 'East Timor'], lat: -8.9, lng: 125.7, region: 'Southeast Asia' },
  { names: ['Togo'], lat: 8.6, lng: 1.2, region: 'Africa' },
  { names: ['Tonga'], lat: -21.2, lng: -175.2, region: 'Oceania' },
  { names: ['Trinidad and Tobago', 'Trinidad'], lat: 10.7, lng: -61.2, region: 'South America' },
  { names: ['Tuvalu'], lat: -7.1, lng: 177.6, region: 'Oceania' },
  { names: ['Vanuatu'], lat: -15.4, lng: 166.9, region: 'Oceania' },
  { names: ['Vatican', 'Vatican City', 'Holy See'], lat: 41.9, lng: 12.45, region: 'Europe' },

  // === MAJOR CITIES ===
  { names: ['New York', 'NYC', 'Manhattan'], lat: 40.71, lng: -74.01, region: 'North America' },
  { names: ['Los Angeles'], lat: 34.05, lng: -118.24, region: 'North America' },
  { names: ['Washington D.C.', 'Washington DC'], lat: 38.91, lng: -77.04, region: 'North America' },
  { names: ['San Francisco'], lat: 37.77, lng: -122.42, region: 'North America' },
  { names: ['Chicago'], lat: 41.88, lng: -87.63, region: 'North America' },
  { names: ['Houston'], lat: 29.76, lng: -95.37, region: 'North America' },
  { names: ['Miami'], lat: 25.76, lng: -80.19, region: 'North America' },
  { names: ['Seattle'], lat: 47.61, lng: -122.33, region: 'North America' },
  { names: ['Boston'], lat: 42.36, lng: -71.06, region: 'North America' },
  { names: ['Atlanta'], lat: 33.75, lng: -84.39, region: 'North America' },
  { names: ['Dallas'], lat: 32.78, lng: -96.80, region: 'North America' },
  { names: ['Denver'], lat: 39.74, lng: -104.99, region: 'North America' },
  { names: ['London'], lat: 51.51, lng: -0.13, region: 'Europe' },
  { names: ['Paris'], lat: 48.86, lng: 2.35, region: 'Europe' },
  { names: ['Berlin'], lat: 52.52, lng: 13.41, region: 'Europe' },
  { names: ['Madrid'], lat: 40.42, lng: -3.70, region: 'Europe' },
  { names: ['Rome'], lat: 41.90, lng: 12.50, region: 'Europe' },
  { names: ['Amsterdam'], lat: 52.37, lng: 4.90, region: 'Europe' },
  { names: ['Brussels'], lat: 50.85, lng: 4.35, region: 'Europe' },
  { names: ['Vienna'], lat: 48.21, lng: 16.37, region: 'Europe' },
  { names: ['Prague'], lat: 50.08, lng: 14.44, region: 'Europe' },
  { names: ['Warsaw'], lat: 52.23, lng: 21.01, region: 'Europe' },
  { names: ['Zurich'], lat: 47.38, lng: 8.54, region: 'Europe' },
  { names: ['Munich'], lat: 48.14, lng: 11.58, region: 'Europe' },
  { names: ['Barcelona'], lat: 41.39, lng: 2.17, region: 'Europe' },
  { names: ['Dublin'], lat: 53.35, lng: -6.26, region: 'Europe' },
  { names: ['Stockholm'], lat: 59.33, lng: 18.07, region: 'Europe' },
  { names: ['Oslo'], lat: 59.91, lng: 10.75, region: 'Europe' },
  { names: ['Helsinki'], lat: 60.17, lng: 24.94, region: 'Europe' },
  { names: ['Copenhagen'], lat: 55.68, lng: 12.57, region: 'Europe' },
  { names: ['Athens'], lat: 37.98, lng: 23.73, region: 'Europe' },
  { names: ['Lisbon'], lat: 38.72, lng: -9.14, region: 'Europe' },
  { names: ['Istanbul'], lat: 41.01, lng: 28.98, region: 'Middle East' },
  { names: ['Ankara'], lat: 39.93, lng: 32.85, region: 'Middle East' },
  { names: ['Moscow'], lat: 55.76, lng: 37.62, region: 'Europe' },
  { names: ['St. Petersburg', 'Saint Petersburg'], lat: 59.93, lng: 30.32, region: 'Europe' },
  { names: ['Kyiv', 'Kiev'], lat: 50.45, lng: 30.52, region: 'Europe' },
  { names: ['Beijing'], lat: 39.90, lng: 116.41, region: 'East Asia' },
  { names: ['Shanghai'], lat: 31.23, lng: 121.47, region: 'East Asia' },
  { names: ['Hong Kong'], lat: 22.32, lng: 114.17, region: 'East Asia' },
  { names: ['Taipei'], lat: 25.03, lng: 121.57, region: 'East Asia' },
  { names: ['Tokyo'], lat: 35.68, lng: 139.69, region: 'East Asia' },
  { names: ['Seoul'], lat: 37.57, lng: 126.98, region: 'East Asia' },
  { names: ['Pyongyang'], lat: 39.04, lng: 125.76, region: 'East Asia' },
  { names: ['Bangkok'], lat: 13.76, lng: 100.50, region: 'Southeast Asia' },
  { names: ['Jakarta'], lat: -6.21, lng: 106.85, region: 'Southeast Asia' },
  { names: ['Manila'], lat: 14.60, lng: 120.98, region: 'Southeast Asia' },
  { names: ['Hanoi'], lat: 21.03, lng: 105.85, region: 'Southeast Asia' },
  { names: ['Ho Chi Minh City', 'Saigon'], lat: 10.82, lng: 106.63, region: 'Southeast Asia' },
  { names: ['Kuala Lumpur'], lat: 3.14, lng: 101.69, region: 'Southeast Asia' },
  { names: ['Mumbai', 'Bombay'], lat: 19.08, lng: 72.88, region: 'South Asia' },
  { names: ['New Delhi', 'Delhi'], lat: 28.61, lng: 77.21, region: 'South Asia' },
  { names: ['Karachi'], lat: 24.86, lng: 67.01, region: 'South Asia' },
  { names: ['Dhaka'], lat: 23.81, lng: 90.41, region: 'South Asia' },
  { names: ['Islamabad'], lat: 33.69, lng: 73.04, region: 'South Asia' },
  { names: ['Kabul'], lat: 34.53, lng: 69.17, region: 'Central Asia' },
  { names: ['Tehran'], lat: 35.69, lng: 51.39, region: 'Middle East' },
  { names: ['Baghdad'], lat: 33.31, lng: 44.37, region: 'Middle East' },
  { names: ['Damascus'], lat: 33.51, lng: 36.29, region: 'Middle East' },
  { names: ['Beirut'], lat: 33.89, lng: 35.50, region: 'Middle East' },
  { names: ['Jerusalem'], lat: 31.77, lng: 35.23, region: 'Middle East' },
  { names: ['Tel Aviv'], lat: 32.09, lng: 34.78, region: 'Middle East' },
  { names: ['Riyadh'], lat: 24.71, lng: 46.67, region: 'Middle East' },
  { names: ['Dubai'], lat: 25.20, lng: 55.27, region: 'Middle East' },
  { names: ['Abu Dhabi'], lat: 24.45, lng: 54.65, region: 'Middle East' },
  { names: ['Doha'], lat: 25.29, lng: 51.53, region: 'Middle East' },
  { names: ['Cairo'], lat: 30.04, lng: 31.24, region: 'Middle East' },
  { names: ['Lagos'], lat: 6.52, lng: 3.38, region: 'Africa' },
  { names: ['Nairobi'], lat: -1.29, lng: 36.82, region: 'Africa' },
  { names: ['Johannesburg'], lat: -26.20, lng: 28.05, region: 'Africa' },
  { names: ['Cape Town'], lat: -33.93, lng: 18.42, region: 'Africa' },
  { names: ['Addis Ababa'], lat: 9.02, lng: 38.75, region: 'Africa' },
  { names: ['Casablanca'], lat: 33.59, lng: -7.59, region: 'Africa' },
  { names: ['Khartoum'], lat: 15.50, lng: 32.56, region: 'Africa' },
  { names: ['Mogadishu'], lat: 2.05, lng: 45.32, region: 'Africa' },
  { names: ['Tripoli'], lat: 32.90, lng: 13.19, region: 'Africa' },
  { names: ['Sydney'], lat: -33.87, lng: 151.21, region: 'Oceania' },
  { names: ['Melbourne'], lat: -37.81, lng: 144.96, region: 'Oceania' },
  { names: ['Mexico City'], lat: 19.43, lng: -99.13, region: 'North America' },
  { names: ['São Paulo', 'Sao Paulo'], lat: -23.55, lng: -46.63, region: 'South America' },
  { names: ['Rio de Janeiro'], lat: -22.91, lng: -43.17, region: 'South America' },
  { names: ['Buenos Aires'], lat: -34.60, lng: -58.38, region: 'South America' },
  { names: ['Lima'], lat: -12.05, lng: -77.04, region: 'South America' },
  { names: ['Bogotá', 'Bogota'], lat: 4.71, lng: -74.07, region: 'South America' },
  { names: ['Santiago'], lat: -33.45, lng: -70.67, region: 'South America' },
  { names: ['Caracas'], lat: 10.48, lng: -66.90, region: 'South America' },
  { names: ['Havana'], lat: 23.11, lng: -82.37, region: 'South America' },

  // === REGIONS ===
  { names: ['Middle East'], lat: 29.0, lng: 42.0, region: 'Middle East' },
  { names: ['Southeast Asia'], lat: 5.0, lng: 110.0, region: 'Southeast Asia' },
  { names: ['Central Asia'], lat: 42.0, lng: 65.0, region: 'Central Asia' },
  { names: ['East Asia'], lat: 35.0, lng: 115.0, region: 'East Asia' },
  { names: ['South Asia'], lat: 22.0, lng: 78.0, region: 'South Asia' },
  { names: ['Central America'], lat: 13.0, lng: -85.0, region: 'South America' },
  { names: ['Balkans'], lat: 42.0, lng: 21.0, region: 'Europe' },
  { names: ['Sahel'], lat: 14.0, lng: 0.0, region: 'Africa' },
  { names: ['Horn of Africa'], lat: 8.0, lng: 45.0, region: 'Africa' },
  { names: ['Caribbean'], lat: 17.0, lng: -70.0, region: 'South America' },
  { names: ['Persian Gulf', 'Gulf states'], lat: 27.0, lng: 51.0, region: 'Middle East' },
  { names: ['Mediterranean'], lat: 36.0, lng: 18.0, region: 'Europe' },
  { names: ['Arctic'], lat: 75.0, lng: 0.0, region: 'Europe' },
  { names: ['Crimea'], lat: 45.3, lng: 34.1, region: 'Europe' },
  { names: ['Donbas', 'Donbass'], lat: 48.0, lng: 38.0, region: 'Europe' },
  { names: ['Kashmir'], lat: 34.1, lng: 74.8, region: 'South Asia' },
  { names: ['Xinjiang'], lat: 41.0, lng: 85.0, region: 'East Asia' },
  { names: ['Tibet'], lat: 31.0, lng: 89.0, region: 'East Asia' },
  { names: ['Golan Heights', 'Golan'], lat: 33.0, lng: 35.8, region: 'Middle East' },
  { names: ['Strait of Hormuz', 'Hormuz'], lat: 26.6, lng: 56.3, region: 'Middle East' },
  { names: ['Taiwan Strait'], lat: 24.0, lng: 119.0, region: 'East Asia' },
  { names: ['Red Sea'], lat: 20.0, lng: 38.5, region: 'Middle East' },
  { names: ['Black Sea'], lat: 43.0, lng: 35.0, region: 'Europe' },
  { names: ['South China Sea'], lat: 12.0, lng: 113.0, region: 'Southeast Asia' },
  { names: ['Pentagon'], lat: 38.87, lng: -77.06, region: 'North America' },
  { names: ['Kremlin'], lat: 55.75, lng: 37.62, region: 'Europe' },
  { names: ['Capitol Hill'], lat: 38.89, lng: -77.01, region: 'North America' },
  { names: ['White House'], lat: 38.90, lng: -77.04, region: 'North America' },
  { names: ['Wall Street'], lat: 40.71, lng: -74.01, region: 'North America' },
  { names: ['Silicon Valley'], lat: 37.39, lng: -122.08, region: 'North America' },
  { names: ['Davos'], lat: 46.80, lng: 9.84, region: 'Europe' },
  { names: ['Geneva'], lat: 46.20, lng: 6.14, region: 'Europe' },
  { names: ['The Hague'], lat: 52.07, lng: 4.30, region: 'Europe' },
]

// Build search index: flatten all name→entry mappings, sorted by name length descending
const INDEX = []
for (const entry of RAW) {
  for (const name of entry.names) {
    INDEX.push({ name: name.toUpperCase(), entry })
  }
}
INDEX.sort((a, b) => b.name.length - a.name.length)

/**
 * Extract the first recognizable location from text.
 * Returns { name, lat, lng, region } or null.
 */
export function extractLocation(text) {
  if (!text) return null
  const upper = text.toUpperCase()
  for (const { name, entry } of INDEX) {
    // Word boundary check: ensure the match isn't part of a larger word
    const idx = upper.indexOf(name)
    if (idx === -1) continue
    const before = idx > 0 ? upper[idx - 1] : ' '
    const after = idx + name.length < upper.length ? upper[idx + name.length] : ' '
    const isBoundary = (c) => !(/[A-Z0-9]/).test(c)
    if (isBoundary(before) && isBoundary(after)) {
      return {
        name: entry.names[0],
        lat: entry.lat,
        lng: entry.lng,
        region: entry.region,
      }
    }
  }
  return null
}
