// Search list — add RSS feed URLs here to pull articles.
// Each entry: { id, name, color, url }
export const NEWS_SOURCES = [
  // Israel / Middle East
  { id: 'jpost', name: 'JPost', color: '#1a56db',
    url: 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx' },
  { id: 'timesofisrael', name: 'Times of Israel', color: '#2266bb',
    url: 'https://www.timesofisrael.com/feed/' },
  { id: 'aljazeera', name: 'Al Jazeera', color: '#cc6600',
    url: 'https://www.aljazeera.com/xml/rss/all.xml' },
  // US / UK / International
  { id: 'reuters', name: 'Reuters', color: '#ff6633',
    url: 'https://www.reutersagency.com/feed/' },
  { id: 'bbc', name: 'BBC World', color: '#bb1100',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml' },
  { id: 'guardian', name: 'The Guardian', color: '#0077bb',
    url: 'https://www.theguardian.com/world/rss' },
  { id: 'nyt', name: 'NY Times', color: '#111111',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml' },
  { id: 'ap', name: 'AP News', color: '#ee3322',
    url: 'https://rsshub.app/apnews/topics/world-news' },
  { id: 'france24', name: 'France 24', color: '#0055aa',
    url: 'https://www.france24.com/en/rss' },
  { id: 'dw', name: 'DW News', color: '#0044aa',
    url: 'https://rss.dw.com/rdf/rss-en-world' },
  // Asia-Pacific
  { id: 'scmp', name: 'SCMP', color: '#cc9900',
    url: 'https://www.scmp.com/rss/91/feed' },
  { id: 'abc-au', name: 'ABC Australia', color: '#006633',
    url: 'https://www.abc.net.au/news/feed/2942460/rss.xml' },
  // Africa
  { id: 'africanews', name: 'Africanews', color: '#228833',
    url: 'https://www.africanews.com/feed/' },
]

export const CATEGORIES = {
  conflict: {
    label: 'CONFLICT',
    keywords: ['war', 'attack', 'military', 'troops', 'bomb', 'missile', 'strike', 'killed',
      'weapons', 'army', 'soldier', 'combat', 'offensive', 'ceasefire', 'airstrike', 'militia',
      'insurgent', 'terror', 'hostage', 'siege', 'explosion', 'drone strike', 'shelling',
      'battlefield', 'casualties', 'wounded', 'gunfire', 'ambush', 'raid', 'hamas', 'hezbollah',
      'idf', 'houthi'],
    badge: 'badge-danger',
  },
  politics: {
    label: 'POLITICS',
    keywords: ['election', 'president', 'minister', 'parliament', 'government', 'vote',
      'campaign', 'diplomat', 'summit', 'treaty', 'sanction', 'policy', 'legislation',
      'congress', 'senate', 'political', 'opposition', 'coalition', 'referendum', 'inaugur',
      'impeach', 'ambassador', 'UN ', 'NATO', 'G7', 'G20', 'European Union', 'knesset',
      'netanyahu', 'biden', 'trump'],
    badge: 'badge-success',
  },
  economy: {
    label: 'ECONOMY',
    keywords: ['economy', 'market', 'trade', 'tariff', 'inflation', 'gdp', 'stock', 'bank',
      'currency', 'debt', 'recession', 'financial', 'investment', 'oil price', 'export',
      'import', 'fiscal', 'budget', 'tax', 'unemployment', 'interest rate', 'federal reserve',
      'central bank', 'crypto', 'bitcoin', 'shekel'],
    badge: 'badge-warning',
  },
  disaster: {
    label: 'DISASTER',
    keywords: ['earthquake', 'flood', 'hurricane', 'typhoon', 'tsunami', 'wildfire', 'drought',
      'volcano', 'cyclone', 'tornado', 'landslide', 'avalanche', 'storm', 'famine',
      'climate', 'emission', 'pollution', 'environmental', 'rescue', 'evacuat'],
    badge: 'badge-warning',
  },
  security: {
    label: 'SECURITY',
    keywords: ['cyber', 'hack', 'breach', 'espionage', 'spy', 'intelligence', 'surveillance',
      'arrest', 'drug', 'trafficking', 'cartel', 'crime', 'prison', 'court', 'trial',
      'verdict', 'convicted', 'smuggl', 'fraud', 'corruption', 'launder', 'mossad',
      'shin bet', 'interpol'],
    badge: 'badge-danger',
  },
  humanitarian: {
    label: 'HUMANITARIAN',
    keywords: ['refugee', 'migrant', 'asylum', 'humanitarian', 'aid', 'crisis', 'famine',
      'displaced', 'NGO', 'red cross', 'UNHCR', 'pandemic', 'outbreak', 'vaccine',
      'disease', 'epidemic', 'health', 'WHO', 'hospital', 'medical', 'starvation',
      'hostage', 'captive', 'relief'],
    badge: 'badge-muted',
  },
  stocks: {
    label: 'STOCKS',
    keywords: ['stock', 'shares', 'nasdaq', 'dow jones', 's&p 500', 'wall street', 'bull market',
      'bear market', 'ipo', 'dividend', 'equity', 'trading', 'rally', 'selloff', 'sell-off',
      'portfolio', 'hedge fund', 'index fund', 'bond yield', 'treasury', 'market cap',
      'earnings report', 'quarterly results', 'stock exchange', 'ftse', 'nikkei', 'hang seng',
      'dax', 'closing bell', 'opening bell'],
    badge: 'badge-stocks',
  },
  terrorism: {
    label: 'TERRORISM',
    keywords: ['terrorist', 'terrorism', 'terror attack', 'suicide bomb', 'car bomb', 'jihad',
      'jihadist', 'extremist', 'radicalis', 'lone wolf', 'isis', 'isil', 'al-qaeda', 'al qaeda',
      'boko haram', 'al-shabaab', 'taliban', 'militant', 'suicide vest', 'mass shooting',
      'stabbing attack', 'vehicle ramming', 'hostage crisis', 'beheading', 'martyrdom'],
    badge: 'badge-danger',
  },
  defense: {
    label: 'DEFENSE',
    keywords: ['defense', 'defence', 'arms deal', 'weapons system', 'missile defense', 'iron dome',
      'patriot missile', 'f-35', 'fighter jet', 'aircraft carrier', 'submarine', 'warship',
      'naval', 'air force', 'pentagon', 'military budget', 'arms race', 'nuclear weapon',
      'nuclear test', 'ballistic missile', 'hypersonic', 'defense contract', 'lockheed',
      'raytheon', 'military exercise', 'joint drill', 'nato exercise', 'deterrence',
      'military aid', 'arms embargo', 'weapons sale'],
    badge: 'badge-defense',
  },
  antisemitism: {
    label: 'ANTISEMITISM',
    keywords: ['antisemit', 'anti-semit', 'anti semit', 'jewish hate', 'hate crime',
      'synagogue attack', 'holocaust denial', 'neo-nazi', 'neo nazi', 'swastika',
      'jewish community', 'pogrom', 'blood libel', 'zionist conspiracy',
      'antizionis', 'boycott israel', 'bds movement', 'jewish target'],
    badge: 'badge-antisemitism',
  },
  maritime: {
    label: 'MARITIME',
    keywords: ['maritime', 'naval', 'shipping', 'cargo ship', 'tanker', 'piracy', 'pirate',
      'sea route', 'strait', 'port', 'harbor', 'coast guard', 'blockade', 'naval base',
      'fleet', 'suez canal', 'panama canal', 'bab al-mandab', 'malacca strait',
      'freedom of navigation', 'territorial waters', 'exclusive economic zone', 'eez',
      'container ship', 'oil tanker', 'seizure at sea', 'maritime security'],
    badge: 'badge-maritime',
  },
  trade: {
    label: 'TRADE',
    keywords: ['trade war', 'trade deal', 'trade agreement', 'free trade', 'trade deficit',
      'trade surplus', 'import duty', 'export ban', 'trade sanction', 'trade embargo',
      'trade negotiation', 'trade dispute', 'wto', 'world trade', 'bilateral trade',
      'trade route', 'supply chain', 'trade partner', 'trade policy', 'protectionism',
      'trade bloc', 'mercosur', 'asean trade', 'trade volume', 'commodity'],
    badge: 'badge-trade',
  },
}

export const REGIONS = [
  'North America', 'South America', 'Europe', 'Middle East',
  'Africa', 'Central Asia', 'South Asia', 'East Asia',
  'Southeast Asia', 'Oceania',
]
